"""init_db

Revision ID: 9fdbdbf89ca9
Revises: 
Create Date: 2023-06-23 12:58:09.516868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdbdbf89ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_employe_id'), 'employe', ['id'], unique=False)
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('employe_username', sa.String(), nullable=True),
    sa.Column('salary_increase_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employe_username'], ['employe.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    op.drop_index(op.f('ix_employe_id'), table_name='employe')
    op.drop_table('employe')
    # ### end Alembic commands ###
